/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-04-06 08:18:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goodsDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:split", org.apache.taglibs.standard.functions.Functions.class, "split", new Class[] {java.lang.String.class, java.lang.String.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:replace", org.apache.taglibs.standard.functions.Functions.class, "replace", new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.2.2.jar", Long.valueOf(1732586084044L));
    _jspx_dependants.put("jar:file:/C:/bookShop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookShop01/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1732498772892L));
    _jspx_dependants.put("jar:file:/C:/bookShop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookShop01/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/bookShop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookShop01/WEB-INF/lib/tiles-jsp-2.2.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1276606224000L));
    _jspx_dependants.put("jar:file:/C:/bookShop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookShop01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write(' ');

     //치환 변수 선언합니다.
      pageContext.setAttribute("crcn", "\r\n"); //개행문자
    //pageContext.setAttribute("crcn" , "\n"); //Ajax로 변경 시 개행 문자 
      pageContext.setAttribute("br", "<br/>"); //br 태그
  /*    
  	 참고. 도서 상품 목차 등에 개행문자(\r\n) 가 포함되어 있으면 웹페이지에서는 이를 <br>태그를 사용해 바꿔줘야 합니다.
  	      즉, 테이블의 상품목차를 웹페이지에 표시하면서 개행 기능을 유지하려면 
  	      개행문자(\r\n)를 <br>태그로 대체해서 표시해야 상품 목차를 등록할때의 형태로 웹페이지에 표시됩니다.
  	      
  	      <textArea>태그 내의 입력한 value값으로 데이터를 불러오기 떄문에 개행문자(엔터키처리한 \r\n문자)가 그대로 표기 되는 반면
  	      홈쇼핑 사이트화면(웹브라우저에 보여지는 화면)에서는 textArea가 아닌 html태그 자체를 불러오기 때문에 <br>태그로 치환해주어야 합니다.
  	      
  	      글을 작성할떄(글쓰기할때) textArea태그에선 개행문자가 \n 입니다.
  	      웹브라우저에는 html태그로 표현되는데 html태그에서 개행문자역할은 <br>태그 입니다. 안바꿔주면 그냥 한줄에 출력됩니다.
  	      
  	      
  	//  "crcn"은 개행문자를 나타내는 이스케이프 시퀀스(escape sequence) 중 하나입니다. 
  	//  "crcn"은 Carriage Return(CR)과 Line Feed(LF)의 조합을 나타내며, 
  	//   일반적으로 텍스트 파일에서 한 줄의 끝을 나타내는 데 사용됩니다.

  	//  Carriage Return은 문자열 커서를 문자열의 맨 앞으로 이동시키는 제어 문자이고, 
  	//  Line Feed는 문자열 커서를 다음 줄로 이동시키는 제어 문자입니다. 
  	//  두 문자를 조합한 "crcn"은 텍스트 파일에서 한 줄을 끝내고 다음 줄로 넘어가는 역할을 합니다.

  	//  참고로, 다른 이스케이프 시퀀스로는 "\n" (Line Feed)과 "\r" (Carriage Return)이 있습니다. 
  	//  이들은 각각 개행문자를 나타내는데 사용됩니다. 
  	//  예를 들어, Unix 및 Linux 운영 체제에서는 일반적으로 "\n"을 사용하고, Windows 운영 체제에서는 "\r\n"을 사용합니다. 
  	      
  	      
  */

      out.write("  \r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("/*\r\n");
      out.write("  #layer라는 ID선택자를 사용하여 div요소영역을 선택해 스타일을 지정하고 있습니다.\r\n");
      out.write("  이 div요소 영역은 다른 요소들 위에 떠있는 배경 레이아웃을 나타내며,\r\n");
      out.write("  z-index속성을 사용하여 다른 요소들과 겹치는 순서를 조정 하고 있습니다.\r\n");
      out.write("  position: absolute 송석을 사용하여 요소를 절대적인 위치에 배치 하고 있으며\r\n");
      out.write("  top과 left속성을 사용하여 왼쪽 상단 모서리를 기준으로 요소를 위치시키고 있습니다.\r\n");
      out.write("  마지막으로 width속성을 사용하여 div요소 영역의 가로 길이를 100%로 설정하고 있습니다. \r\n");
      out.write("*/\r\n");
      out.write("#layer {\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0px;\r\n");
      out.write("	left: 0px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("	#popup라는 ID선택자를 사용하여 <div id=\"popup\">팝업창 요소 영역을 스타일링하고 있습니다.\r\n");
      out.write("    이 <div>요소는 position: fixed 속성을 사용하여 화면의 고정된 위치에 배치되며,\r\n");
      out.write("    text-align : center 속성을 사용하여 텍스트를 <div>의 가운데로 정렬하고 있습니다.\r\n");
      out.write("    left와 top속성을 사용하여  요소를 중앙에 배치하고 있으며,\r\n");
      out.write("    width와 height속성을 사용하여 <div>요소영역의 크기를 지정하고 있습니다.\r\n");
      out.write("    이 <div>요소의 배경색과 테두리 색상은 각각 background-color와 border속성을 사용하여 지정하고 있습니다.\r\n");
      out.write("*/\r\n");
      out.write("#popup {\r\n");
      out.write("	z-index: 3;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	top: 45%;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("	background-color: #ccffff;\r\n");
      out.write("	border: 3px solid #87cb42;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("	#close라는 ID선택자를 사용하여 닫기 X 이미지 버튼을 보이는 <img>태그를 선택해 스타일링 하고 있습니다.\r\n");
      out.write("	이 <img>요소는 float:right 속성을 사용하여 x이미지가 우측 상단으로 배치되며 \r\n");
      out.write("	z-index속성을 사용하여 다른요소들보다 위에 위치하도록 조정하고 있습니다.\r\n");
      out.write("*/\r\n");
      out.write("#close {\r\n");
      out.write("	z-index: 4;\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    //장바구니 버튼을 클릭하면 호출되는 함수로~~\r\n");
      out.write("    //도서 상품 번호를 매개변수로 전달 받아!\r\n");
      out.write("    //\r\n");
      out.write("	function add_cart(goods_id) {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			async : false, //false인 경우 동기식으로 처리한다.\r\n");
      out.write("			\r\n");
      out.write("			//Ajax를 이용해 장바구니에 추가할 상품 번호를 전송 하여 장바구니에 상품 추가 요청을 합니다. \r\n");
      out.write("			url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/addGoodsInCart.do\",\r\n");
      out.write("			data : { goods_id:goods_id },\r\n");
      out.write("			success : function(data, textStatus) {\r\n");
      out.write("// 						장바구니테이블에 추가할 상품이 이미 존재하면? \"already_existed\" 메세지를 받고\r\n");
      out.write("// 						존재하지 않으면? 장바구니 테이블에 새 상품을 추가INSERT하고 나서?\r\n");
      out.write("// 						'add_success'메세지를  위 data매개변수로 받는다.\r\n");
      out.write("				//alert(data);\r\n");
      out.write("			//	$('#message').append(data);\r\n");
      out.write("				if(data.trim()=='add_success'){ //장바구니 테이블에 새상품을 추가하고 메세지를 받으면?\r\n");
      out.write("					\r\n");
      out.write("						imagePopup('open', '.layer01');	\r\n");
      out.write("				\r\n");
      out.write("				}else if(data.trim()=='already_existed'){//장바구니 테이블에 \r\n");
      out.write("														 //사이트 이용자가 추가할 상품이 이미 저장되어 있으면?\r\n");
      out.write("					\r\n");
      out.write("					alert(\"이미 카트에 등록된 상품입니다.\");	\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			error : function(data, textStatus) {\r\n");
      out.write("				alert(\"에러가 발생했습니다.\"+data);\r\n");
      out.write("			},\r\n");
      out.write("			complete : function(data, textStatus) {\r\n");
      out.write("				//alert(\"작업을완료 했습니다\");\r\n");
      out.write("			}\r\n");
      out.write("		}); //end ajax	\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 팝업창의 x 이미지를 감싸고 있는 <a>태그를 클랙했을때 호출되는 함수 \r\n");
      out.write("	function imagePopup(type) {\r\n");
      out.write("		\r\n");
      out.write("		if (type == 'open') {\r\n");
      out.write("			// 팝업창을 연다.\r\n");
      out.write("			$('#layer').attr('style', 'visibility:visible');\r\n");
      out.write("\r\n");
      out.write("			// 페이지를 가리기위한 레이어 영역의 높이를 페이지 전체의 높이와 같게 한다.\r\n");
      out.write("			$('#layer').height(jQuery(document).height());\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		else if (type == 'close') {\r\n");
      out.write("\r\n");
      out.write("			// 팝업창을 닫는다.\r\n");
      out.write("			$('#layer').attr('style', 'visibility:hidden');\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("//구매하기 버튼을 누르면 호출되는 함수로 현재보고 있는 도서상품의 번호, 제목, 정가가격, 도서이미지명을 매개변수로 받아서 처리   \r\n");
      out.write("function fn_order_each_goods(goods_id,goods_title,goods_sales_price,fileName){\r\n");
      out.write("	\r\n");
      out.write("	//id속성값이 isLogOn인 태그를 선택해서  _isLogOn변수에 저장\r\n");
      out.write("	//<input type=\"hidden\" name=\"isLogOn\" id=\"isLogOn\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLogOn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("	var _isLogOn=document.getElementById(\"isLogOn\");\r\n");
      out.write("	\r\n");
      out.write("	//<input type=\"hidden\" name=\"isLogOn\" id=\"isLogOn\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLogOn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> 태그의 value속성에 적힌 값 얻어\r\n");
      out.write("	//var isLogOn변수에 저장 \r\n");
      out.write("	var isLogOn=_isLogOn.value;  //\"false\" 또는 \"true\"\r\n");
      out.write("	\r\n");
      out.write("	 if(isLogOn == \"false\" || isLogOn == '' ){\r\n");
      out.write("		alert(\"로그인 후 주문이 가능합니다!!!\");\r\n");
      out.write("	} \r\n");
      out.write("	\r\n");
      out.write("	var total_price,final_total_price;\r\n");
      out.write("	//id속성값이 order_goods_qty인 <select>태그 내부의 선택한 <option> 구매수량의 정보를 가져오기 위해 <select>태그 선택해오기 \r\n");
      out.write("	/*\r\n");
      out.write("	도서 상품 구매 수량 선택하는 태그를 선택함 \r\n");
      out.write("	     <select style=\"width: 60px;\" id=\"order_goods_qty\">\r\n");
      out.write("    		<option value=\"1\">1</option>\r\n");
      out.write("			<option value=\"2\">2</option>\r\n");
      out.write("			<option>3</option>\r\n");
      out.write("			<option>4</option>\r\n");
      out.write("			<option>5</option>\r\n");
      out.write("  		</select>\r\n");
      out.write("	 */	\r\n");
      out.write("	var order_goods_qty=document.getElementById(\"order_goods_qty\");\r\n");
      out.write("	\r\n");
      out.write("   	//<form></form>\r\n");
      out.write("	var formObj=document.createElement(\"form\");\r\n");
      out.write("	\r\n");
      out.write("	//<input>\r\n");
      out.write("	var i_goods_id = document.createElement(\"input\"); \r\n");
      out.write("	 //<input name=\"goods_id\">\r\n");
      out.write("    i_goods_id.name=\"goods_id\";\r\n");
      out.write("    //<input name=\"goods_id\" value=\"매개변수 goods_id로 전달 받는 상품번호\">\r\n");
      out.write("    i_goods_id.value=goods_id;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("	//<input>\r\n");
      out.write("    var i_goods_title = document.createElement(\"input\");\r\n");
      out.write("	//<input name=\"goods_title\">\r\n");
      out.write("    i_goods_title.name=\"goods_title\";\r\n");
      out.write("    //<input name=\"goods_title\" vlaue=\"매개변수 goods_title로 전달받는 도서상품제목\">\r\n");
      out.write("    i_goods_title.value=goods_title;\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    //<input>\r\n");
      out.write("    var i_goods_sales_price=document.createElement(\"input\");\r\n");
      out.write("	//<input name=\"goods_sales_price\">\r\n");
      out.write("    i_goods_sales_price.name=\"goods_sales_price\";\r\n");
      out.write("    //<input name=\"goods_sales_price\" value=\"매개변수 goods_sales_price로 전달받는 도서상품판매가격\">\r\n");
      out.write("    i_goods_sales_price.value=goods_sales_price;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   	//<input>\r\n");
      out.write("    var i_fileName=document.createElement(\"input\");\r\n");
      out.write("	//<input name=\"goods_fileName\">\r\n");
      out.write("    i_fileName.name=\"goods_fileName\";\r\n");
      out.write("	//<input name=\"goods_fileName\" value=\"매개변수 fileName으로 전달받는 도서상품 이미지파일명\">\r\n");
      out.write("    i_fileName.value=fileName;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    //<input>\r\n");
      out.write("    var i_order_goods_qty=document.createElement(\"input\");\r\n");
      out.write("  	//<input name=\"order_goods_qty\">\r\n");
      out.write("    i_order_goods_qty.name=\"order_goods_qty\";\r\n");
      out.write("  	//<input name=\"order_goods_qty\" value=\"select option태그에서 선택한 구매수량을 설정\"> \r\n");
      out.write("    i_order_goods_qty.value = order_goods_qty.value;\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    formObj.appendChild(i_goods_id);\r\n");
      out.write("    formObj.appendChild(i_goods_title);\r\n");
      out.write("    formObj.appendChild(i_goods_sales_price);\r\n");
      out.write("    formObj.appendChild(i_fileName);\r\n");
      out.write("    formObj.appendChild(i_order_goods_qty);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    document.body.appendChild(formObj); \r\n");
      out.write("    \r\n");
      out.write("    formObj.method=\"post\";\r\n");
      out.write("    formObj.action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderEachGoods.do\";\r\n");
      out.write("    /*\r\n");
      out.write("    <body>\r\n");
      out.write("	  	<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderEachGoods.do\" method=\"post\">\r\n");
      out.write("	  		<input name=\"goods_id\" value=\"매개변수 goods_id로 전달 받는 상품번호\">\r\n");
      out.write("	  		<input name=\"goods_title\" vlaue=\"매개변수 goods_title로 전달받는 도서상품제목\">\r\n");
      out.write("	  		<input name=\"goods_sales_price\" value=\"매개변수 goods_sales_price로 전달받는 도서상품판매가격\">\r\n");
      out.write("	  		<input name=\"goods_fileName\" value=\"매개변수 fileName으로 전달받는 도서상품 이미지파일명\">\r\n");
      out.write("	  		<input name=\"order_goods_qty\" value=\"select option태그에서 선택한 구매수량을 설정\">\r\n");
      out.write("	  	</form>  \r\n");
      out.write("	 </body>  \r\n");
      out.write("*/      \r\n");
      out.write("    formObj.submit();//구매 요청!\r\n");
      out.write("	}	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<hgroup>\r\n");
      out.write("		<h1>컴퓨터와 인터넷</h1>\r\n");
      out.write("		<h2>국내외 도서 &gt; 컴퓨터와 인터넷 &gt; 웹 개발</h2>\r\n");
      out.write("		<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("		<h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" &nbsp; 저| ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_publisher}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("	</hgroup>\r\n");
      out.write("	<div id=\"goods_image\">\r\n");
      out.write("		<figure>\r\n");
      out.write("			<img alt=\"HTML5 &amp; CSS3\"\r\n");
      out.write("				src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/thumbnails.do?goods_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&fileName=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		</figure>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"detail_table\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"fixed\">정가</td>\r\n");
      out.write("					<td class=\"active\"><span >\r\n");
      out.write("					   ");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				         ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원\r\n");
      out.write("					</span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"dot_line\">\r\n");
      out.write("					<td class=\"fixed\">판매가</td>\r\n");
      out.write("					<td class=\"active\"><span >\r\n");
      out.write("					   ");
      if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				         ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${discounted_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원(10%할인)</span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"fixed\">포인트적립</td>\r\n");
      out.write("					<td class=\"active\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("P(10%적립)</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"dot_line\">\r\n");
      out.write("					<td class=\"fixed\">포인트 추가적립</td>\r\n");
      out.write("					<td class=\"fixed\">만원이상 구매시 1,000P, 5만원이상 구매시 2,000P추가적립 편의점 배송 이용시 300P 추가적립</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"fixed\">발행일</td>\r\n");
      out.write("					<td class=\"fixed\">\r\n");
      out.write("					   ");
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					 ");
      out.write("\r\n");
      out.write("					   ");
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					   ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"fixed\">페이지 수</td>\r\n");
      out.write("					<td class=\"fixed\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_total_page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("쪽</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"dot_line\">\r\n");
      out.write("					<td class=\"fixed\">ISBN</td>\r\n");
      out.write("					<td class=\"fixed\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_isbn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"fixed\">배송료</td>\r\n");
      out.write("					<td class=\"fixed\"><strong>무료</strong></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"fixed\">배송안내</td>\r\n");
      out.write("					<td class=\"fixed\">\r\n");
      out.write("						<strong>[당일배송]</strong> 당일배송 서비스 시작!<br> \r\n");
      out.write("						<strong>[휴일배송]</strong>\r\n");
      out.write("						휴일에도 배송받는 Bookshop\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"fixed\">도착예정일</td>\r\n");
      out.write("					<td class=\"fixed\">지금 주문 시 내일 도착 예정</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"fixed\">수량</td>\r\n");
      out.write("					<td class=\"fixed\">\r\n");
      out.write("					      <select style=\"width: 60px;\" id=\"order_goods_qty\">\r\n");
      out.write("				      		<option>1</option>\r\n");
      out.write("							<option>2</option>\r\n");
      out.write("							<option>3</option>\r\n");
      out.write("							<option>4</option>\r\n");
      out.write("							<option>5</option>\r\n");
      out.write("					     </select>\r\n");
      out.write("					 </td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a class=\"buy\" href=\"javascript:fn_order_each_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_sales_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\">구매하기 </a></li>\r\n");
      out.write("			<li><a class=\"cart\" href=\"javascript:add_cart('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\">장바구니</a></li>\r\n");
      out.write("			\r\n");
      out.write("			<li><a class=\"wish\" href=\"#\">위시리스트</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"clear\"></div>\r\n");
      out.write("	<!-- 내용 들어 가는 곳 -->\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<ul class=\"tabs\">\r\n");
      out.write("			<li><a href=\"#tab1\">책소개</a></li>\r\n");
      out.write("			<li><a href=\"#tab2\">저자소개</a></li>\r\n");
      out.write("			<li><a href=\"#tab3\">책목차</a></li>\r\n");
      out.write("			<li><a href=\"#tab4\">출판사서평</a></li>\r\n");
      out.write("			<li><a href=\"#tab5\">추천사</a></li>\r\n");
      out.write("			<li><a href=\"#tab6\">리뷰</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<div class=\"tab_container\">\r\n");
      out.write("			<div class=\"tab_content\" id=\"tab1\">\r\n");
      out.write("				<h4>책소개</h4>\r\n");
      out.write("				<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:replace(goods.goods_intro,crcn,br)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</p>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"tab_content\" id=\"tab2\">\r\n");
      out.write("				<h4>저자소개</h4>\r\n");
      out.write("				<p>\r\n");
      out.write("				<div class=\"writer\">저자 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("				\r\n");
      out.write("				 ");
      out.write("\r\n");
      out.write("				 <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:replace(goods.goods_writer_intro,crcn,br) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</p> \r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"tab_content\" id=\"tab3\">\r\n");
      out.write("				<h4>책목차</h4>\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:replace(goods.goods_contents_order,crcn,br)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</p> \r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"tab_content\" id=\"tab4\">\r\n");
      out.write("				<h4>출판사서평</h4>\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				 <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:replace(goods.goods_publisher_comment ,crcn,br)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</p> \r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"tab_content\" id=\"tab5\">\r\n");
      out.write("				<h4>추천사</h4>\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:replace(goods.goods_recommendation,crcn,br) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"tab_content\" id=\"tab6\">\r\n");
      out.write("				<h4>리뷰</h4>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"clear\"></div>\r\n");
      out.write("	<div id=\"layer\" style=\"visibility: hidden\">\r\n");
      out.write("		<!-- visibility:hidden 으로 설정하여 해당 div안의 모든것들을 가려둔다. -->\r\n");
      out.write("		<div id=\"popup\">\r\n");
      out.write("			<!-- 팝업창 닫기  X 이미지 버튼 -->\r\n");
      out.write("			<a href=\"javascript:\" onClick=\"javascript:imagePopup('close', '.layer01');\"> \r\n");
      out.write("				<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/close.png\" id=\"close\" />\r\n");
      out.write("			</a> \r\n");
      out.write("			<br /> \r\n");
      out.write("			<font size=\"12\" id=\"contents\">장바구니에 담았습니다.</font>\r\n");
      out.write("			<br>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<form   action='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/myCartList.do'  >				\r\n");
      out.write("					<input  type=\"submit\" value=\"장바구니 보기\">\r\n");
      out.write("			</form>			\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>		\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<input type=\"hidden\" name=\"isLogOn\" id=\"isLogOn\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLogOn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/goods/goodsDetail.jsp(15,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/goods/goodsDetail.jsp(15,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsDetail.jsp(15,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/goods/goodsDetail.jsp(19,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("goods");
      // /WEB-INF/views/goods/goodsDetail.jsp(19,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsDetail.jsp(19,0) '${goodsMap.goodsVO}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${goodsMap.goodsVO}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/goods/goodsDetail.jsp(20,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("imageList");
      // /WEB-INF/views/goods/goodsDetail.jsp(20,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsDetail.jsp(20,0) '${goodsMap.imageList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${goodsMap.imageList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /WEB-INF/views/goods/goodsDetail.jsp(276,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/goods/goodsDetail.jsp(276,8) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("number");
      // /WEB-INF/views/goods/goodsDetail.jsp(276,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setVar("goods_price");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
      // /WEB-INF/views/goods/goodsDetail.jsp(283,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_price*0.9}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/goods/goodsDetail.jsp(283,8) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setType("number");
      // /WEB-INF/views/goods/goodsDetail.jsp(283,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setVar("discounted_price");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/views/goods/goodsDetail.jsp(297,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("pub_date");
      // /WEB-INF/views/goods/goodsDetail.jsp(297,8) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsDetail.jsp(297,8) '${goods.goods_published_date}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${goods.goods_published_date}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent(null);
      // /WEB-INF/views/goods/goodsDetail.jsp(307,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("arr");
      // /WEB-INF/views/goods/goodsDetail.jsp(307,8) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsDetail.jsp(307,8) '${fn:split(pub_date,' ')}'",_jsp_getExpressionFactory().createValueExpression(new org.apache.jasper.el.ELContextWrapper(_jspx_page_context.getELContext(),_jspx_fnmap_0),"${fn:split(pub_date,' ')}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/goods/goodsDetail.jsp(308,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${arr[0]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/goods/goodsDetail.jsp(371,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("image");
      // /WEB-INF/views/goods/goodsDetail.jsp(371,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsDetail.jsp(371,4) '${imageList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${imageList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/download.do?goods_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&fileName=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
